sudo: false

language: php

php:
    - '8.0'

before_script:
    - composer install --no-interaction --prefer-dist

script:
    - bin/php-cs-fixer fix --verbose --diff --dry-run src/
    - bin/phpspec run -n
